---
# PLAY 1: Bootstrap the Server (Fix Missing Dependencies)
- name: Bootstrap Server Requirements
  hosts: all
  gather_facts: false
  become: false  # Important: Run as ec2-user, don't try to become root yet
  tasks:
    - name: Install ACL package via raw SSH
      raw: sudo dnf install -y acl
      changed_when: false

# PLAY 2: The Actual Application Deployment
- name: Deploy Fedora Lane App
  hosts: all
  become: true   # Now we can become root safely
  gather_facts: false

  tasks:
    - name: Install Apache (httpd)
      ansible.builtin.dnf:
        name: httpd
        state: present
        use_backend: dnf4

    - name: Start and Enable Service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
        
    - name: Deploy Dynamic Web Page
      ansible.builtin.copy:
        content: |
          <html>
          <body style="font-family: sans-serif; text-align: center; padding: 50px;">
            <div style="border: 2px solid #0077cc; padding: 20px; border-radius: 10px; display: inline-block;">
              <h1 style="color: #0077cc;">🚀 Fedora Lane App</h1>
              <h2>{{ custom_message }}</h2>
              <p>Updated via Ansible Survey</p>
            </div>
          </body>
          </html>
        dest: /var/www/html/index.html
        mode: '0644'
