---
- name: Deploy Fedora Lane App
  hosts: all
  become: true
  vars:
    web_content: |
      <html><body style="background-color:#e6f7ff; text-align:center; padding:50px;">
      <div style="border:4px solid #0077cc; padding:20px; display:inline-block; border-radius:10px;">
      <h1 style="color:#0077cc;">🚀 Fedora Lane App</h1>
      <p>Status: <strong>OPERATIONAL</strong></p>
      <p>Version: 1.0 (Deployed by Ansible)</p>
      </div></body></html>

  tasks:
    - name: Install Apache (httpd)
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Start and Enable Service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Deploy Application Code
      ansible.builtin.copy:
        content: "{{ web_content }}"
        dest: /var/www/html/index.html
        mode: '0644'
