---
- name: Auto-Heal Web Server
  hosts: all
  become: true
  gather_facts: false
  
  tasks:
    - name: 1. Force Apache Service Restart
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: 2. Restore Critical Data (Index File)
      ansible.builtin.copy:
        content: "<html><body><h1 style='color:green'>✅ System Restored</h1><p>Maintenance completed by Ansible Automation Platform.</p></body></html>"
        dest: /var/www/html/index.html
        mode: '0644'
