---
- name: Fix Netdata issues
  hosts: all
  become: yes

  tasks:
    - name: Ensure Netdata config dir exists
      file:
        path: /etc/netdata
        state: directory

    - name: Restart Netdata
      systemd:
        name: netdata
        state: restarted

    - name: Wait for Netdata to respond
      uri:
        url: http://localhost:19999
        status_code: 200
        timeout: 5
