---
- name: Install Netdata on Amazon Linux
  hosts: all
  become: yes

  tasks:
    - name: Install required packages
      yum:
        name:
          - curl
          - bash
        state: present

    - name: Download Netdata kickstart script
      get_url:
        url: https://my-netdata.io/kickstart.sh
        dest: /tmp/netdata-kickstart.sh
        mode: '0755'

    - name: Install Netdata
      command: /tmp/netdata-kickstart.sh --dont-wait --stable-channel
      args:
        creates: /usr/sbin/netdata

    - name: Ensure Netdata service is enabled and running
      systemd:
        name: netdata
        enabled: yes
        state: started
