---
- name: Install Netdata on Amazon Linux 2023
  hosts: all
  become: yes

  tasks:
    - name: Ensure bash is installed (curl-minimal already exists)
      yum:
        name: bash
        state: present

    - name: Download Netdata kickstart script
      get_url:
        url: https://my-netdata.io/kickstart.sh
        dest: /tmp/netdata-kickstart.sh
        mode: '0755'

    - name: Install Netdata
      command: /tmp/netdata-kickstart.sh --dont-wait --stable-channel
      args:
        creates: /usr/sbin/netdata

    - name: Enable and start Netdata
      systemd:
        name: netdata
        enabled: yes
        state: started
