---
- name: Monitor Web Server Health
  hosts: all
  gather_facts: false
  
  tasks:
    - name: Check Website Status (Internal)
      ansible.builtin.uri:
        url: "http://localhost"
        status_code: 200
        return_content: no
      register: result
      ignore_errors: true

    - name: Report Failure if Site is Down
      ansible.builtin.fail:
        msg: "CRITICAL ALERT: Web Server is unreachable!"
      when: result.status is undefined or result.status != 200
